us_holidays_2025:
  - "2025-01-01" # New Year's Day
  - "2025-01-20" # MLK Day
  - "2025-02-17" # Presidents' Day
  - "2025-05-26" # Memorial Day
  - "2025-07-04" # Independence Day
  - "2025-09-01" # Labor Day
  - "2025-11-27" # Thanksgiving
  - "2025-12-25" # Christmas Day
