regions:
  north:
    lat_range: [42, 49]
    hvac_mult: 1.3
    dehum_mult: 1.0
    lighting_winter_mult: 1.4
    irrigation_mult: 0.8
    solar_mult: 0.8
    storm_burst_mult: 1.2
  south:
    lat_range: [25, 35]
    hvac_mult: 1.5
    dehum_mult: 1.6
    lighting_winter_mult: 1.2
    irrigation_mult: 1.3
    solar_mult: 1.1
    storm_burst_mult: 1.2
  arid_west:
    lat_range: [32, 40]
    hvac_mult: 1.1
    dehum_mult: 0.6
    lighting_winter_mult: 1.2
    irrigation_mult: 1.6
    solar_mult: 1.2
    storm_burst_mult: 1.1
  marine_west:
    lat_range: [37, 49]
    hvac_mult: 1.0
    dehum_mult: 1.2
    lighting_winter_mult: 1.3
    irrigation_mult: 0.9
    solar_mult: 0.9
    storm_burst_mult: 1.1
  east_midwest:
    lat_range: [35, 45]
    hvac_mult: 1.2
    dehum_mult: 1.1
    lighting_winter_mult: 1.3
    irrigation_mult: 1.0
    solar_mult: 1.0
    storm_burst_mult: 1.2
